### ISSUE TITLE
msedgedriver.exe not being copied to all projects

### ISSUE THREAD

**Issue by HugoSousa** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#11]
**Describe the bug**
msedgedriver.exe is being copied on build to the project bin folder where the Selenium.WebDriver.MSEdgeDriver NuGet package is installed. However, the same does not happen when building projects with dependency of the previous one.

Example: 
Project A - has Selenium.WebDriver.MSEdgeDriver installed
Project B - has project A as dependency
On building project B, msedgedriver.exe is not copied to the bin folder. This is not the behavior with chromedriver.exe - it does get copied to project B bin folder on build.

**To Reproduce**
1. Create project A and project B. Set Project A as a dependency of Project B. 
2. Install NuGet Selenium.WebDriver.MSEdgeDriver in project A.
3. Build project A - msedgedriver.exe is copied to bin folder.
4. Build project B - msedgedriver.exe is NOT copied to bin folder.

**Expected behavior**
msedgedriver.exe should be copied in step 4 above. This is the behavior for chromedriver.exe.

**Additional context**
I've done some troubleshooting and compared the MSBuild targets file with the Selenium.WebDriver.ChromeDriver NuGet package, since this has the correct behavior.

ChromeDriver MSBuild target file:
![image](https://user-images.githubusercontent.com/6798502/138317475-74d27696-0bbd-4d95-a7af-d6f997e978ab.png)

MSEdgeDriver MSBuild target file:
![image](https://user-images.githubusercontent.com/6798502/138317548-7f49f8a8-d5ac-406c-8118-3871749e1fa3.png)

I've modified the MSEdgeDriver MSBuild target file to match the ChromeDriver, that is removing the `<Choose>` and `<When>` tags from the file. That seemed to work and the .exe started getting copied to the folder, as expected.

Is there any reason why this is different in MSEdgeDriver? Shouldn't this have the same behavior?

**Comment by leandrodotec** [comment]
Hi @HugoSousa, 
Thanks for your help.

I tried changing the definitions to exactly the same as Chrome driver and still didn't work.  Then I tested Chrome driver with a Unit test depending on a Library and chromedriver.exe  doesn't get copied to the  Unit test's bin folder either.

I created a branch called "Issue-11" with both edge driver and chrome driver tests.  Please have a look.

**Comment by leandrodotec** [comment]
Hi again, 

I added changes to another branch "Issue-11-solution" where I change UnitTest.csproj and add a <COPY> command. 


```
<Target Name="CopyMsEdgeDriverToBin" BeforeTargets="AfterBuild">
  <Copy SourceFiles="$(SolutionDir)MsEdgeClient\bin\$(Configuration)\$(TargetFramework)\msedgedriver.exe" DestinationFolder="$(TargetDir)" SkipUnchangedFiles="true"/>
  <Message Text="$(MSBuildProjectName) -> $(SolutionDir)MsEdgeClient\bin\$(Configuration)\$(TargetFramework)\msedgedriver.exe" Importance="high" />
</Target>
```

**Comment by leandrodotec** [comment]
Basically I couldn't find a way to make the parent project copy files from the child project via nuget packages definitions.

**Comment by SamJ26** [comment]
Hey, I had the same issue with `msedgedriver.exe` not being copied to all projects. I found out I didn't have `<PublishMsEdgeDriver>true</PublishMsEdgeDriver>` in `.csproj` file in project containing this nuget package. Now it works, without problems 🙂. It would be great to extend README to contain all the information about this package. something like this https://github.com/jsakamoto/nupkg-selenium-webdriver-chromedriver. Or at least mention requirement of `<PublishMsEdgeDriver>true</PublishMsEdgeDriver>` in `.csproj` file.

**Comment by leandrodotec** [comment]
Thanks @SamJ26 , that worked perfectly.  I will update the example and extend README.
