### ISSUE TITLE
Please update to v95.x

### ISSUE THREAD

**Issue by jbcrowley** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#12]
**Describe the bug**
The MSEdge version in the NuGet package is not current with the public release channel version.

**To Reproduce**
Compare the current version available with what's released on https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/.

**Expected behavior**
The version to match what's on the official public release channel version.

**Comment by leandrodotec** [comment]
Hi. This is a side project that I started when I was working part-time. Now I am working full-time and can't keep up with weekly/daily releases. I try to update once every 3 weeks and I always release future versions as a pre-release. If you can't find the version you are looking for in the current package, it is very likely you will find as prerelease.
