### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by DeLaphante** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#2]
Can you update the package please as its currently stuck at version 81 while the latest Edge is on version 83.

Thanks

**Comment by leandrodotec** [comment]
Hi @DeLaphante, thanks for the heads up. Just updated it.

**Comment by DeLaphante** [comment]
> Hi @DeLaphante, thanks for the heads up. Just updated it.

Great - thanks!
