### ISSUE TITLE
Linux driver is actually the MacOS driver

### ISSUE THREAD

**Issue by Sebazzz** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#20]
**Describe the bug**
The Linux driver is in Mach-O format:

```
file ./driver/linux64/msedgedriver                                                                                                                             ❮   126
./driver/linux64/msedgedriver: Mach-O 64-bit x86_64 executable, flags:<NOUNDEFS|DYLDLINK|TWOLEVEL|PIE|HAS_TLV_DESCRIPTORS>
```

**To Reproduce**
Download Nuget package (100.0.1185.36 tested) and extract. Chmod +x the edge driver and run under Ubuntu x64.

```
 cannot execute binary file: Exec format error
```

**Comment by goelhardik** [comment]
We saw the same issue. 

I think this line has the bug: https://github.com/leandrodotec/nupkg-selenium-webdriver-msedgedriver/blob/master/BuildPackage.bat#L13

**Comment by Sebazzz** [comment]
PR submitted. Good catch!
