### ISSUE TITLE
Rename the DefinePropertiesMSEdgeDriver.targets file

### ISSUE THREAD

**Issue by christianbumann** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#22]
As in this files are only properties, imho this file should named `DefinePropertiesMSEdgeDriver.props` instead

**Comment by leandrodotec** [comment]
Hi, I actually tried to follow what people are doing in the Chrome driver and they use DefinePropertiesMSEdgeDriver.targets.

I might be wrong, I will have a look.
