### ISSUE TITLE
Missing version 102 and 103

### ISSUE THREAD

**Issue by ashiitaka** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#23]
There are missing newest version 103 and 102. I would really appreciate if you could add them

**Comment by Napoleon10** [comment]
Hello Git people, the Edge Browser is now 103.0.1264.37. The latest version for msedgedriver is 101.0.1210.47 in Visual Studio.
I am testing using SpecFlow and this has broken all my tests with the message: '_This version of MSEdgeDriver only supports MSEdge version 101 Current browser version is 103.0.1264.37 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe (SessionNotCreated)_'

Could you advise when there might be a resolution.

Regards, 

Napoleon10

**Comment by shamp00** [comment]
A quick temporary fix while waiting for the new version is just to copy the drivers from [Microsoft's Edge developer website](https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/) into the platform subfolders in `<Solution folder>\packages\Selenium.WebDriver.MSEdgeDriver.101.0.1210.47\driver_ folder\`.

**Comment by dove** [comment]
102 is available a pre-release package.  Could this be done for 103 too? I'd be happy to give it a test run and report back.

**Comment by leandrodotec** [comment]
Hi everybody.  yeah, so normally I tried to release the stable version plus as normal version release and the newer ones as pre-release. 
So when there is a new stable version change from 102 to 103, people can at least use the 103 pre-release package.

I have a full time job as a developer and do this on my free time (that I would like to spend being with my family, going to the gym, or having beers)  so once every 2 weeks I get the latest releases and publish the packages.

Sometimes I take longer than 2 weeks, so if anyone wants to contribute, please let me know.
