### ISSUE TITLE
License.txt not SPDX compliant

### ISSUE THREAD

**Issue by marobbins** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#24]
**Is your feature request related to a problem? Please describe.**
Automated component governance tools flag components that don't contain SPDX licenses. Although "Free as a bird" is delightful, it requires enterprise users of this excellent tool to regularly manually upload their own interpretation of the license.

**Describe the solution you'd like**
The license, as written, is substantively equivalent the WTFPL, the full text of which reads: "Do whatever the fuck you want." This is semantically equivalent to "Free as a bird," and has the benefit of being recognized by SPDX. Replacing license.txt with a copy of that license would make clear to users the rights they hold.

**Describe alternatives you've considered**
Although I believe the WTFPL is the closest SPDX license in spirit to license.txt as it's currently written, the Creative Commons 0 clause license (CC0) offers the same set of rights, and does so in a more verbose and "grown up" fashion. If you want to leave "Free as a bird," you could also add the text of either license beneath it, or minimally a reference to a specific license.

**Additional context**
[clearlydefined
](https://clearlydefined.io/?type=nuget&sortDesc=true&sort=releaseDate&name=Selenium.WebDriver.MSEdgeDriver) shows inconsistencies across different versions of the package, due exclusively to the reliance on human volunteers to curate license information for each release.
[license.txt](https://github.com/leandrodotec/nupkg-selenium-webdriver-msedgedriver/files/9561824/license.txt)

**Comment by leandrodotec** [comment]
Hi @marobbins,  I did this a long time ago and I didn't know what I was doing.  

Do you have a good license.txt file ? If yes, can you make a pull request please?

Thank you.

**Comment by marobbins** [comment]
PR submitted with the unLicense. Feel free to find a different one that better suits your desires.

**Comment by leandrodotec** [comment]
I added these 2 versions with new LICENSE file
[106.0.1370.17](https://www.nuget.org/packages/Selenium.WebDriver.MSEdgeDriver/106.0.1370.17)
[106.0.1370.26](https://www.nuget.org/packages/Selenium.WebDriver.MSEdgeDriver/106.0.1370.26)
