### ISSUE TITLE
Wrong Driver being downloaded

### ISSUE THREAD

**Issue by BigIan1969** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#26]
**Describe the bug**
The Edgedriver downloaded by the nuget package Selenium.WebDriver.MSEdgeDriver is msedgedriver.exe, but the EdgeDriver(...) constructor is looking for MicrosoftWebDriver.exe.

**To Reproduce**

                    driver = new EdgeDriver();

**Expected behavior**
Should launch Edge

**Actual Behaviour**
I get the following:
OpenQA.Selenium.DriverServiceNotFoundException: 'The msedgedriver.exe file does not exist in the current directory or in a directory on the PATH environment variable. The driver can be downloaded at https://developer.microsoft.com/en-us/microsoft-edge/tools/webdriver/.'

**Desktop (please complete the following information):**
 - OS: W11
 - Browser MSEdge
 - Version 105.0.1343.53

**Comment by leandrodotec** [comment]
Hi @BigIan1969.

I can't reproduce this issue with the new versions, can you check again please?

**Comment by ramiabughazaleh** [comment]
For `MicrosoftWebDriver.exe`, you'll have to use a different NuGet package, like `Selenium.WebDriver.MicrosoftWebDriver` for example.
