### ISSUE TITLE
Linux edge driver not available with version 107.0.1418.35 or higher

### ISSUE THREAD

**Issue by nihar06** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#27]
**Describe the bug**
Package does not have Linux driver for 107.0.1418.35 or higher.

**To Reproduce**
1. Add a package ref in project. or download driver manually from: https://www.nuget.org/packages/Selenium.WebDriver.MSEdgeDriver/107.0.1418.35
2. Run on linux OS or unzip driver.

**Expected behavior**
Package should have msedgedriver for linux. 

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser Edge
 - NuGet Package version: 107.0.1418.35

**Additional context**
I was able to find driver on https://msedgedriver.azureedge.net/107.0.1418.35/edgedriver_linux64.zip
So, expecting to have on NuGet package.

**Comment by leandrodotec** [comment]
Closing this one as duplicated with #29 .
