### ISSUE TITLE
Moving between webview2 and WPF windows the edge driver seems to fail to reconnect causing commands to not process

### ISSUE THREAD

**Issue by ashrussell** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#30]
**Describe the bug**
When automating moving between webview2 and WPF windows the edge driver seems to fail to reconnect to the webview2 view  
Found this with while attempting to automate a UI user journey scenario using winappdriver and edgedriver 

**To Reproduce**

1. Perform some operations in a WPF form (winappdriver would be doing this in my test)
2. Click on a link which opens a webview 2 form (edgedriver doing this and a new edge driver initialised when the form is opened)
3. Return to WPF form
4. Perform some assertions on the WPF form that webview2 form has done some stuff  
5. Return to the webview 2 form (new driver set up)
6. Attempt to perform changes with the edge driver but no clicks or inputs appear to work 

**Expected behavior**
I would expect that we can reaccess the webview with the edge driver as the application under test has not quit or ended unexpectedly

**Desktop (please complete the following information):**
 - OS: windows 10
 - Browser msedge, 107.0.1418.56 (Official build) (64-bit) -

**Comment by leandrodotec** [comment]
Hi,

@ashrussell, this project is only about packaging the MSEdge driver into a nuget package.  For issues with the driver, go to the edge selenium tools here: https://github.com/microsoft/edge-selenium-tools
