### ISSUE TITLE
Not seeing the latest edge driver 115

### ISSUE THREAD

**Issue by iamsarathbaskaran** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#33]
**Describe the bug**
Latest edge driver v115 not available on nuget package manager

**To Reproduce**
https://www.nuget.org/packages/Selenium.WebDriver.MSEdgeDriver

**Expected behavior**
Expected the latest edge driver v115.x to be available in nuget package manager but could see the last being v114.0.1823.58

**Comment by erif89** [comment]
I think this issue can be closed. Though I am interested in where I can find information on when each version is released and when a prerelease becomes an official release.

**Comment by leandrodotec** [comment]
Hi, usually, I publish  current packages as normal releases and future versions as pre-releases. The challenge is that I can't keep up with Edge driver development cycle and I am always behind. 

I am looking for contributors to help. I am a solo developer that have a full-time job.
