### ISSUE TITLE
EdgeDriver Version

### ISSUE THREAD

**Issue by Napoleon10** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#34]
**Describe the bug**
Enquiry to when the lastest browser verion - 117.0.2045.31 for edge be available for Selenium.WebDriver.MSEdgeDriver? 
Automation tests are failing while using Visual Studio and SpecFlow.

Regards, John.

**Comment by YogeshJayaseelan** [comment]
@kboesel Any idea how long it will take or any alternative solutions to bring the latest version in the Nugget Package Manager Solution

**Comment by Napoleon10** [comment]
This is the longest I have experienced of the driver being out of sync with browser version! I am now using Chrome and ChromeOptions to replace Edge and EdgeOptions. This is the smallest amount of code change that I have found, Cheers...

**Comment by ChrisBloom-TH** [comment]
On alternate solutions Selenium Manager is pretty good & fully integrated with the core Selenium packages you already have if you're on the latest version of Selenium. Just don't have any edge driver .exe file in your bin directory (so uninstall this package & clean the build directory) or in any folders of your configured system path & it'll auto download then use the correct version of the driver matching your installed edge version.

**Comment by YogeshJayaseelan** [comment]
@ChrisBloom- I have removed the edgedriver.exe form the bin folder and also uninstalled the Selenium.Webdriver.EdgeBrowser package and i did clean the project. But, still im getting the below error 

'An error occurred trying to start process -C:\ProjectFolder\bin\Debug\net6.0\msedgedriver.exe' with working directory 'C:\ProjectFolder\bin\Debug\net6.0'. The system cannot find the file specified.

**Comment by kboesel** [comment]
For what it's worth, there is a pre-release version of the package on Nuget https://www.nuget.org/packages/Selenium.WebDriver.MSEdgeDriver/116.0.1938.36-pre, that for me, works with Edge version 117.x

**Comment by Napoleon10** [comment]
Thanks @kboesel for link info. I might try that. 
This issue highlights the weakness of this entire software system. My understanding is that the Dev's of this Edge Driver (along with other software) don't get paid, and, this wears thin over the long period; because people have lives and things change! What we need is a Dev 'with no life'! :) - Or to get some form of renumeration. All this talk of automation, yet we are in a situation of a world wide monolithic company, Microsoft that has a browser, and then to automate it, we have this situation! If I am wrong let me know.

I also had an error in trying other options. 
Using visual studio with SpecFlow, when testing, wraps the automation up as a Nuget package that is sent to the 'test host' for execution, hence the need for Edge Driver Nuget package. Cheers...

**Comment by YogeshJayaseelan** [comment]
@kboesel  @ChrisBloom-TH  @Napoleon10  - 
Finally i could see the latest version of MS Edge in the NuGet Package Manager. But, this is time its too late for the latest version!!

**Comment by Napoleon10** [comment]
@YogeshJayaseelan @ChrisBloom-TH , I'm not sure who is meant to close this issues, Dev's or the people that raise these issues, however, I have the option to close this off and have not heard from the Dev's?! Regards, John.
