### ISSUE TITLE
Newer version

### ISSUE THREAD

**Issue by MBJScott** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#38]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**
Looking for a newer version other than 119.0.2151.42. Will there be a version for 120?

**Comment by ramiabughazaleh** [comment]
There have already been new versions published to NuGet since 119.0.2151.42:
120.0.2210.144
122.0.2365.63
122.0.2365.92
123.0.2420.65

**Comment by MBJScott** [comment]
Thank you for the information. I have updated my version with the newest one.  As of 5-28-24 my company is running 125.0.2535.67 will the version I see now 124.0.2478.10-pre be compatible?

**Comment by icnocop** [comment]
Yes, `Selenium.WebDriver.MSEdgeDriver 124.0.2478.10-pre` works with `Microsoft Edge 125.0.2535.67` for me.

**Comment by MBJScott** [comment]
Thank you so very much. I appreciate you.  👍
