### ISSUE TITLE
Support for Microsoft Edge WebDriver / Browser version 125

### ISSUE THREAD

**Issue by ramiabughazaleh** [leandrodotec/nupkg-selenium-webdriver-msedgedriver#41]
`Selenium.WebDriver.MSEdgeDriver` version `123.0.2420.65` only supports Microsoft Edge version 123.
I have Microsoft Edge version `125.0.2535.51` installed.

I'd like the stable version of the package to be updated to support Microsoft Edge version 125.

I've created [PR#40](https://github.com/leandrodotec/nupkg-selenium-webdriver-msedgedriver/pull/40) to automatically determine and download the latest Microsoft Edge WebDriver, run BuildPackage.bat, and push the package to nuget, using GitHub actions. 

I'm hoping we can use Github actions to make it easier to build and deploy new versions periodically.

```
System.InvalidOperationException: session not created: This version of Microsoft Edge WebDriver only supports Microsoft Edge version 123
Current browser version is 125.0.2535.51 with binary path C:\Program Files (x86)\Microsoft\Edge\Application\msedge.exe (SessionNotCreated)
```

**Comment by kwilson-93** [comment]
@leandrodotec

**Comment by ramiabughazaleh** [comment]
In the meantime, using `Selenium.WebDriver.MSEdgeDriver` version `124.0.2478.10-pre` works with Microsoft Edge `125.0.2535.51`.
